export {default as Section_one}from "./Section_one"
export {default as Section_two}from "./Section_two"
export {default as Section_three}from "./Section_three"
export {default as Section_fouree}from "./Section_fouree"
export {default as Section_five} from "./Section_five"
export{ default as HomeWrap}from "./HomeWrap"